# -*- coding: utf-8 -*-
"""R_markDown.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1394RARdkUIPod7saZV-LluDOwBoVLezy
"""

# Commented out IPython magic to ensure Python compatibility.
# %load_ext rpy2.ipython

# Commented out IPython magic to ensure Python compatibility.
# %%R
# install.packages(
#   c("rmarkdown", "knitr", "tidyverse", "htmltools"),
#   repos = "https://cloud.r-project.org"
# )

# Commented out IPython magic to ensure Python compatibility.
# %%R
# library(rmarkdown)
# library(knitr)
# library(tidyverse)
# library(htmltools)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# rmd_text <- '
# ---
# title: "Statistical Analysis of the Iris Dataset"
# author: "Md. Fahad Hossain"
# date: "August 2026"
# output:
#   html_document:
#     toc: true
#     toc_float: true
#     theme: cosmo
# ---
# 
# # 1. Introduction
# 
# This report demonstrates how **R Markdown** can combine statistical analysis,
# R code, tables, visualizations, and written interpretation in a single
# reproducible document.
# 
# The Iris dataset contains measurements of iris flowers from three species:
# *setosa*, *versicolor*, and *virginica*.
# 
# # 2. Load the Data
# 
# ```{r setup, message=FALSE, warning=FALSE}
# library(tidyverse)
# data(iris)
# ```
# 
# The first six observations are:
# 
# ```{r}
# head(iris)
# ```
# 
# # 3. Data Overview
# 
# ```{r}
# str(iris)
# summary(iris)
# ```
# 
# The dataset contains `r nrow(iris)` observations and `r ncol(iris)` variables.
# 
# # 4. Descriptive Statistics
# 
# ```{r}
# iris %>%
#   summarise(
#     Mean_Sepal_Length = mean(Sepal.Length),
#     SD_Sepal_Length = sd(Sepal.Length),
#     Mean_Petal_Length = mean(Petal.Length),
#     SD_Petal_Length = sd(Petal.Length)
#   )
# ```
# 
# The average Sepal Length is approximately
# **`r round(mean(iris$Sepal.Length), 2)` cm**.
# 
# The average Petal Length is approximately
# **`r round(mean(iris$Petal.Length), 2)` cm**.
# 
# # 5. Visualization
# 
# ```{r fig.width=7, fig.height=4.5}
# ggplot(iris, aes(x = Sepal.Length,
#                  y = Petal.Length,
#                  color = Species)) +
#   geom_point(size = 2) +
#   geom_smooth(method = "lm", se = FALSE, color = "black") +
#   theme_minimal() +
#   labs(
#     title = "Relationship Between Sepal Length and Petal Length",
#     x = "Sepal Length",
#     y = "Petal Length"
#   )
# ```
# 
# The scatter plot suggests a positive relationship between Sepal Length
# and Petal Length.
# 
# # 6. Simple Linear Regression
# 
# We fit the following model:
# 
# **Petal Length = beta0 + beta1(Sepal Length) + error**
# 
# ```{r}
# model <- lm(Petal.Length ~ Sepal.Length, data = iris)
# summary(model)
# ```
# 
# The estimated regression equation is:
# 
# **Petal Length = `r round(coef(model)[1], 3)` +
# `r round(coef(model)[2], 3)` × Sepal Length**
# 
# The R-squared value is **`r round(summary(model)$r.squared, 3)`**.
# 
# # 7. Interpretation
# 
# The coefficient of Sepal Length is positive, indicating that larger
# Sepal Length tends to be associated with larger Petal Length.
# 
# The regression model explains approximately
# **`r round(summary(model)$r.squared * 100, 1)`%**
# of the variation in Petal Length.
# 
# The p-value for Sepal Length is
# **`r format.pval(summary(model)$coefficients[2,4], digits=3)`**,
# indicating a statistically significant linear relationship.
# 
# # 8. Prediction
# 
# Suppose a new flower has a Sepal Length of 5.5 cm.
# 
# ```{r}
# new_flower <- data.frame(Sepal.Length = 5.5)
# predict(model, new_flower)
# ```
# 
# The predicted Petal Length is approximately
# **`r round(predict(model, data.frame(Sepal.Length = 5.5)), 2)` cm**.
# 
# # 9. Conclusion
# 
# The analysis demonstrates a complete statistical reporting workflow
# using R Markdown.
# 
# The Iris dataset was explored using descriptive statistics and
# visualization, followed by a simple linear regression model.
# 
# The analysis found a statistically significant positive relationship
# between Sepal Length and Petal Length.
# 
# R Markdown makes the analysis reproducible because the code, results,
# graphs, and interpretation are maintained together in a single document.
# 
# # 10. Reproducibility
# 
# This report was generated automatically from an R Markdown file.
# 
# To regenerate the report, simply run:
# 
# ```{r eval=FALSE}
# rmarkdown::render("Iris_Statistical_Report.Rmd")
# ```
# '
# 
# writeLines(rmd_text, "Iris_Statistical_Report.Rmd")
# 
# cat("R Markdown file created successfully!\n")
# file.exists("Iris_Statistical_Report.Rmd")

# Commented out IPython magic to ensure Python compatibility.
# %%R
# output_file <- rmarkdown::render(
#   "Iris_Statistical_Report.Rmd",
#   output_format = "html_document",
#   quiet = FALSE
# )
# 
# output_file

print('Iris_Statistical_Report.Rmd')
print('Iris_Statistical_Report.html')

# Commented out IPython magic to ensure Python compatibility.
# %%R
# html_file <- "Iris_Statistical_Report.html"
# 
# html_content <- paste(
#   readLines(html_file, warn = FALSE),
#   collapse = "\n"
# )
# 
# htmltools::HTML(html_content)

# This cell uses Python only for downloading the generated HTML file.
from google.colab import files
files.download("Iris_Statistical_Report.html")

